// DEMO ONLY: do not import this file from production routes. Enable only with explicit DEMO_MODE=true.
import type {
  AIBrainRule,
  AIPromptTemplate,
  BrandProfile,
  MediaAsset,
  SocialPost,
  SystemLog,
} from "@/lib/social-types";

export const mockBrandProfile: BrandProfile = {
  name: "MYINC Creative Suite",
  publicName: "MYINC",
  site: "https://myinc.com.br",
  instagram: "@myinc.ai",
  facebook: "facebook.com/myinc.ai",
  whatsapp: "+55 11 99999-0000",
  email: "contato@myinc.com.br",
  region: "Brasil, atuação nacional",
  niche: "Marketing premium, IA criativa e automação de social media",
  segment: "SaaS B2B para marcas que querem publicar com consistência",
  primaryAudience: "Empreendedores, agências boutique e gestores de marketing sem equipe grande",
  secondaryAudience: "Consultores, infoprodutores e prestadores de serviço premium",
  persona: "Dono de negócio exigente, visual, sem tempo e que precisa aprovar tudo rapidamente",
  problemsSolved:
    "Falta de constância, criativos genéricos, briefing fraco, atraso de aprovação e publicação manual",
  benefits:
    "Planejamento mensal em minutos, memória de marca, revisão humana e publicação automatizada",
  differentiators:
    "Cérebro da IA editável, prompt mestre auditável, score de qualidade e biblioteca de referências",
  products: "Assinatura MYINC Social Media AI, pacote de templates premium, onboarding de marca",
  services: "Estratégia de conteúdo, configuração de IA, gestão de publicação e revisão criativa",
  averageTicket: "R$ 997 a R$ 4.997/mês",
  objections:
    "Medo de parecer genérico, receio de publicar sem controle, dúvidas sobre conexão com Meta",
  guarantees: "Fluxo com aprovação humana, modo semi-automático por padrão e logs completos",
  socialProof: "Cases com redução de 80% no tempo de produção mensal",
  cases: "Marca local que saiu de 6 para 30 posts/mês mantendo padrão visual",
  testimonials: "A MYINC virou nosso social media interno sem perder a cara da marca.",
  faq: "Como conectar Meta? Como aprovar antes de publicar? Como subir referências?",
  tone: "Premium, direto, confiante, humano e sem exageros",
  communicationStyle:
    "Frases curtas, foco em clareza, CTA direto e vocabulário de marketing sofisticado",
  preferredWords: "premium, estratégia, clareza, automação, consistência, conversão",
  forbiddenWords: "milagre, garantido, viralize instantaneamente, fórmula secreta",
  usualPhrases: "Qualidade de agência. Controle de dono. Velocidade de IA.",
  neverUsePhrases: "Ganhe dinheiro dormindo; resultado garantido em 24h",
  forbiddenPromises: "Prometer faturamento ou crescimento sem contexto e prova",
  allowedTechnicalTerms: "prompt mestre, score, API, automação, briefing criativo",
  avoidedTechnicalTerms: "jargões de infraestrutura sem explicação para usuário final",
  primaryPalette: "Grafite profundo #171717, branco, cinzas neutros e laranja MYINC #F97316",
  secondaryPalette: "Areia claro, carvão, âmbar suave",
  forbiddenColors: "Azul predominante, neon excessivo, roxo como cor principal",
  brandFonts: "Plus Jakarta Sans, Inter, Sans moderna arredondada",
  preferredVisualStyle: "Minimalista premium, tecnológico, limpo, alto contraste e respiro",
  forbiddenVisualStyle: "Poluído, infantil, genérico, banco de imagem artificial sem direção",
  preferredImages: "Mockups elegantes, interfaces reais, pessoas profissionais, luz controlada",
  avoidedImages: "Mãos deformadas, textos pequenos, excesso de elementos, logos inventados",
  logoRules: "Aplicar logo com respiro, preferir assinatura discreta e nunca distorcer proporção",
  compositionRules: "Grid limpo, foco único, hierarquia forte e CTA legível",
  imageTextRules: "Pouco texto, alto contraste, nada de letras pequenas ou distorcidas",
  approvedReferences: "Criativos premium com fundo grafite, cards brancos e destaque laranja",
  badReferences: "Artes com poluição visual, sombras duras e cores aleatórias",
};

export const aiBrainRules: AIBrainRule[] = [
  {
    id: "r1",
    name: "Distribuição estratégica mensal",
    category: "Planejamento",
    content:
      "Respeitar a distribuição informada pelo usuário entre venda, autoridade, relacionamento, prova social e institucional. Priorizar 30 publicações em até 15 minutos de revisão.",
    active: true,
    priority: 1,
    defaultContent: "Distribua o calendário equilibrando venda, autoridade e relacionamento.",
  },
  {
    id: "r2",
    name: "Copy curta e conversacional",
    category: "Copy",
    content:
      "Criar legendas curtas, objetivas, comerciais e sem promessas exageradas. Abrir com gancho claro e fechar com CTA direto.",
    active: true,
    priority: 2,
    defaultContent: "Escreva copy clara, curta e com CTA.",
  },
  {
    id: "r3",
    name: "Design premium MYINC",
    category: "Design",
    content:
      "Usar estética minimalista, grafite, branco, cinzas e laranja MYINC. Evitar azul predominante, excesso de texto e aparência de template genérico.",
    active: true,
    priority: 1,
    defaultContent: "Crie design limpo e premium.",
  },
  {
    id: "r4",
    name: "Negative prompt fixo",
    category: "Imagem",
    content:
      "baixa qualidade, design amador, excesso de texto, letras distorcidas, logo falso, poluição visual, imagem genérica, composição ruim, baixa resolução, aparência infantil, layout desorganizado",
    active: true,
    priority: 1,
    defaultContent: "Evitar baixa qualidade e aparência genérica.",
  },
  {
    id: "r5",
    name: "Roteiro de Reels em 4 blocos",
    category: "Vídeo/Reels",
    content:
      "Todo Reels deve ter gancho de 3 segundos, 3 a 5 cenas, texto na tela, narração objetiva, trilha sugerida e CTA final.",
    active: true,
    priority: 3,
    defaultContent: "Gancho, cenas, narração e CTA.",
  },
];

export const aiPromptTemplates: AIPromptTemplate[] = [
  {
    id: "p1",
    name: "Prompt base para planejamento mensal",
    content:
      "Atue como estrategista de social media premium. Gere um calendário mensal respeitando marca, distribuição, formatos, canais e temas personalizados.",
    note: "Usado antes de criar post_ideas.",
    versions: ["V1 inicial", "V2 com temas personalizados"],
  },
  {
    id: "p2",
    name: "Prompt base para copy",
    content:
      "Atue como copywriter sênior brasileiro. Escreva legenda curta, clara, comercial, sem promessas proibidas e com CTA direto.",
    note: "Usado em generatePostCopy.",
    versions: ["V1 inicial"],
  },
  {
    id: "p3",
    name: "Prompt base para imagem",
    content:
      "Crie uma arte publicitária premium para [canal/formato], no tamanho [dimensão], para a marca [nome], seguindo cores, tom visual e estilo da memória de marca.",
    note: "Segue o modelo oficial de prompt de imagem.",
    versions: ["V1 com negative prompt"],
  },
  {
    id: "p4",
    name: "Prompt base para Reels",
    content:
      "Gere gancho de 3 segundos, roteiro curto, cenas, texto na tela, narração, trilha, thumbnail e legenda.",
    note: "Usado em vídeos curtos.",
    versions: ["V1 inicial"],
  },
  {
    id: "p5",
    name: "Prompt base para melhoria de design",
    content:
      "Analise o criativo, os comentários humanos e o score. Sugira uma versão mais premium, limpa e aderente à marca.",
    note: "Usado em regeneração.",
    versions: ["V1 inicial"],
  },
];

export const mockPosts: SocialPost[] = [
  {
    id: "post-001",
    brandId: "brand-myinc",
    monthlyPlanId: "plan-2026-06",
    title: "Como planejar 30 posts sem virar refém do calendário",
    channel: "Instagram",
    format: "Feed 1080x1350",
    scheduledAt: "2026-06-02T09:00:00-03:00",
    objective: "Autoridade",
    theme: "Planejamento mensal com IA",
    headline: "30 posts. 15 minutos. Controle total.",
    shortText: "Transforme briefing em calendário aprovável sem perder padrão de marca.",
    caption:
      "Planejar conteúdo não precisa consumir sua semana. Com memória de marca, regras de IA e revisão humana, você transforma ideias soltas em um mês inteiro de publicações prontas para aprovar.\n\nQuer acelerar seu calendário? Comece pelo planejamento mensal.",
    hashtags: ["#socialmedia", "#inteligenciaartificial", "#marketingpremium", "#myinc"],
    cta: "Criar planejamento mensal",
    imagePrompt:
      "Crie uma arte publicitária premium para Instagram Feed, no tamanho 1080x1350, para a marca MYINC, seguindo grafite, branco, cinzas e laranja MYINC. A peça deve parecer criada por uma agência profissional de design e marketing, com composição limpa, alto contraste, estética moderna, elementos bem posicionados, visual sofisticado e foco em conversão. Tema da peça: planejamento de 30 posts em 15 minutos. Objetivo: autoridade e conversão. Público-alvo: donos de negócios e gestores de marketing. Negative prompt: baixa qualidade, design amador, excesso de texto, letras distorcidas, logo falso, poluição visual, imagem genérica, composição ruim, baixa resolução, aparência infantil, layout desorganizado.",
    masterPrompt:
      "DADOS DA MARCA: MYINC, marketing premium, tom direto. DADOS DO CONTEÚDO: Feed Instagram, autoridade, junho. CÉREBRO DA IA: copy curta, design premium, negative prompt fixo. BIBLIOTECA: referências grafite e laranja. FEEDBACK: usar como referência futura.",
    creativeBrief:
      "Card vertical premium com dashboard abstrato, número 30 em destaque, CTA discreto em laranja e logo aplicado com respiro.",
    mediaUrl: "",
    qualityScore: 94,
    status: "aprovado",
    humanComments: [
      {
        id: "c1",
        author: "Marina",
        comment: "Use menos texto na arte e deixe o 30 mais forte.",
        status: "resolvido",
        createdAt: "2026-05-27 14:20",
      },
    ],
    versions: [
      {
        id: "v1",
        version: "V1",
        caption: "Planeje o mês com IA.",
        mediaUrl: "",
        qualityScore: 82,
        createdAt: "2026-05-27",
      },
      {
        id: "v2",
        version: "V2",
        caption: "Planejar conteúdo não precisa consumir sua semana.",
        mediaUrl: "",
        qualityScore: 94,
        createdAt: "2026-05-28",
      },
    ],
    feedbacks: ["Gostei", "Usar como referência futura", "Excelente"],
  },
  {
    id: "post-002",
    brandId: "brand-myinc",
    monthlyPlanId: "plan-2026-06",
    title: "Bastidores: IA criando briefing criativo",
    channel: "Instagram",
    format: "Reels 1080x1920",
    scheduledAt: "2026-06-04T18:30:00-03:00",
    objective: "Relacionamento",
    theme: "Bastidores de automação criativa",
    headline: "A IA não substitui seu olhar. Ela acelera.",
    shortText: "Mostre o processo guiado: memória, prompt mestre, revisão e aprovação.",
    caption:
      "O melhor conteúdo nasce quando estratégia, marca e revisão humana trabalham juntos. A IA acelera a primeira versão. Você mantém o controle final.",
    hashtags: ["#reelsbrasil", "#ia", "#criativos", "#automacao"],
    cta: "Ver Cérebro da IA",
    imagePrompt:
      "Crie thumbnail premium vertical para Reels 1080x1920 com interface escura, blocos de prompt mestre e brilho laranja discreto.",
    videoPrompt:
      "Gancho 0-3s: 'Você ainda cria posts do zero?'. Cenas: dashboard, prompt mestre, score, aprovação. Narração objetiva. CTA: configure seu Cérebro da IA.",
    masterPrompt:
      "Marca MYINC + Reels + bastidores + regra de roteiro em 4 blocos + referências aprovadas de dashboard escuro.",
    creativeBrief:
      "Reels com cortes rápidos, textos grandes na tela, trilha tecnológica e thumbnail com contraste alto.",
    mediaUrl: "",
    qualityScore: 88,
    status: "aguardando_revisao",
    humanComments: [
      {
        id: "c2",
        author: "Carlos",
        comment: "Faça uma versão mais comercial no CTA final.",
        status: "aberto",
        createdAt: "2026-05-28 10:05",
      },
    ],
    versions: [
      {
        id: "v1",
        version: "V1",
        caption: "A IA acelera. Você aprova.",
        mediaUrl: "",
        qualityScore: 88,
        createdAt: "2026-05-28",
      },
    ],
    feedbacks: ["Copy fraca"],
  },
  {
    id: "post-003",
    brandId: "brand-myinc",
    monthlyPlanId: "plan-2026-06",
    title: "Mês do trabalhador: consistência também é produtividade",
    channel: "Ambos",
    format: "Carrossel 5 páginas",
    scheduledAt: "2026-06-06T12:00:00-03:00",
    objective: "Institucional",
    theme: "Mês do trabalhador",
    headline: "Produtividade não é fazer mais. É fazer melhor.",
    shortText: "Carrossel institucional com 5 páginas sobre automação confiável.",
    caption:
      "Para equipes pequenas, consistência é vantagem competitiva. Automatize o operacional e preserve o que mais importa: estratégia, criatividade e relacionamento.",
    hashtags: ["#produtividade", "#socialmedia", "#marketingdigital"],
    cta: "Agendar campanha",
    imagePrompt:
      "Carrossel 5 páginas, 1080x1350, estética premium MYINC, composição limpa, contraste grafite/branco/laranja, tema produtividade e trabalho inteligente.",
    masterPrompt:
      "Tema personalizado Mês do trabalhador, 7 publicações, objetivo institucional e comercial, formatos feed/story/reels.",
    creativeBrief:
      "P1 capa forte, P2 problema, P3 método, P4 prova, P5 CTA. Pouco texto por slide.",
    mediaUrl: "",
    qualityScore: 76,
    status: "em_producao",
    humanComments: [],
    versions: [
      {
        id: "v1",
        version: "V1",
        caption: "Produtividade com qualidade.",
        mediaUrl: "",
        qualityScore: 76,
        createdAt: "2026-05-28",
      },
    ],
    feedbacks: ["Design fraco"],
  },
  {
    id: "post-004",
    brandId: "brand-myinc",
    monthlyPlanId: "plan-2026-06",
    title: "Oferta: setup completo de memória de marca",
    channel: "Facebook",
    format: "Facebook 1200x630",
    scheduledAt: "2026-06-08T16:00:00-03:00",
    objective: "Venda",
    theme: "Oferta de onboarding",
    headline: "Sua IA só cria bem quando conhece sua marca.",
    shortText: "Oferta direta para configurar memória, biblioteca e regras de IA.",
    caption:
      "Configure sua base de marca uma vez e acelere todas as próximas campanhas. O setup MYINC organiza tom de voz, visual, referências, produtos, objeções e regras de aprovação.",
    hashtags: ["#marketing", "#automacao", "#facebookads"],
    cta: "Solicitar setup",
    imagePrompt:
      "Post Facebook 1200x630 premium, oferta de setup de memória de marca, card branco sobre fundo grafite e botão laranja.",
    masterPrompt:
      "Venda + Facebook + oferta + objeções + prova social + regras anti-promessa exagerada.",
    creativeBrief: "Peça horizontal, título forte, benefício claro, selo 'Setup guiado' e CTA.",
    mediaUrl: "",
    qualityScore: 47,
    status: "erro",
    errorMessage: "URL pública HTTPS da mídia não configurada para publicação Meta.",
    humanComments: [
      {
        id: "c3",
        author: "Marina",
        comment: "Troque o fundo para mais premium e revise a promessa.",
        status: "aberto",
        createdAt: "2026-05-28 16:45",
      },
    ],
    versions: [
      {
        id: "v1",
        version: "V1",
        caption: "Setup completo para sua IA.",
        mediaUrl: "",
        qualityScore: 47,
        createdAt: "2026-05-28",
      },
    ],
    feedbacks: ["Muito genérico", "Fora da marca"],
  },
];

export const mediaAssets: MediaAsset[] = [
  {
    id: "m1",
    name: "Logo MYINC claro",
    type: "Logo",
    url: "/src/assets/myinc-logo-white.png",
    status: "ativo",
    tags: ["logo", "claro"],
    notes: "Usar em fundos escuros com respiro.",
    uploadedAt: "2026-05-20",
    origin: "Upload da marca",
    aiAllowed: true,
    campaign: "Marca",
    format: "PNG",
  },
  {
    id: "m2",
    name: "Dashboard premium grafite",
    type: "Referência visual",
    url: "",
    status: "referência aprovada",
    tags: ["dashboard", "premium", "grafite"],
    notes: "Inspiração de interface limpa. Não copiar layout.",
    uploadedAt: "2026-05-21",
    origin: "Referências de Alto Padrão",
    aiAllowed: true,
    campaign: "Institucional",
    format: "Feed",
  },
  {
    id: "m3",
    name: "Template carrossel autoridade",
    type: "Template",
    url: "",
    status: "template",
    tags: ["carrossel", "autoridade"],
    notes: "Base para 5 a 8 páginas.",
    uploadedAt: "2026-05-22",
    origin: "Biblioteca",
    aiAllowed: true,
    campaign: "Autoridade",
    format: "Carrossel",
  },
  {
    id: "m4",
    name: "Exemplo poluído concorrente",
    type: "Print concorrente",
    url: "",
    status: "referência proibida",
    tags: ["não usar", "poluído"],
    notes: "Evitar excesso de elementos e azul predominante.",
    uploadedAt: "2026-05-23",
    origin: "Concorrente",
    aiAllowed: false,
    campaign: "Restrições",
    format: "Feed",
  },
];

export const systemLogs: SystemLog[] = [
  {
    id: "l1",
    date: "2026-05-29 09:12",
    type: "Teste de conexão",
    user: "Admin",
    module: "Painel ADM",
    status: "alerta",
    friendlyMessage: "Conexão Meta ainda não configurada.",
    technicalDetail: "META_PAGE_ACCESS_TOKEN ausente no ambiente.",
  },
  {
    id: "l2",
    date: "2026-05-29 09:18",
    type: "Geração de planejamento",
    user: "Marina",
    module: "Planejamento mensal",
    status: "sucesso",
    friendlyMessage: "30 ideias geradas respeitando distribuição de formatos.",
    technicalDetail: "generateMonthlyPlan returned 30 post_ideas with 7 custom campaign items.",
  },
  {
    id: "l3",
    date: "2026-05-29 09:24",
    type: "Erro Meta",
    user: "Sistema",
    module: "Publicação",
    status: "erro",
    friendlyMessage: "A mídia precisa estar em uma URL pública HTTPS antes de publicar.",
    technicalDetail: "validatePublicMediaUrl failed: PUBLIC_MEDIA_BASE_URL empty.",
    postId: "post-004",
  },
  {
    id: "l4",
    date: "2026-05-29 09:30",
    type: "Comentário humano",
    user: "Carlos",
    module: "Estúdio Criativo",
    status: "info",
    friendlyMessage: "Comentário enviado para melhorar a próxima versão.",
    technicalDetail: "content_comments.insert post-002 status aberto.",
  },
];

export const statusTone: Record<string, string> = {
  rascunho: "bg-muted text-muted-foreground border-border",
  tema_aprovado: "bg-primary/12 text-primary border-primary/25",
  em_producao: "bg-warning/15 text-warning border-warning/30",
  aguardando_revisao: "bg-accent text-accent-foreground border-border",
  aprovado: "bg-success/15 text-success border-success/25",
  agendado: "bg-primary/12 text-primary border-primary/25",
  publicado: "bg-success/15 text-success border-success/25",
  erro: "bg-destructive/15 text-destructive border-destructive/25",
  pausado: "bg-warning/15 text-warning border-warning/30",
  arquivado: "bg-muted text-muted-foreground border-border",
  reprovado: "bg-destructive/15 text-destructive border-destructive/25",
};

export const channelTone: Record<string, string> = {
  Instagram: "bg-primary/12 text-primary border-primary/25",
  Facebook: "bg-card text-foreground border-border",
  Ambos: "bg-gradient-primary text-primary-foreground border-transparent",
};

export const requiredDatabaseTables = [
  "users",
  "brands",
  "brand_profiles",
  "brand_voice_rules",
  "brand_visual_rules",
  "brand_products",
  "brand_services",
  "brand_references",
  "brand_forbidden_terms",
  "brand_preferred_terms",
  "brand_assets",
  "monthly_plans",
  "custom_campaign_themes",
  "post_ideas",
  "posts",
  "post_versions",
  "content_comments",
  "media_assets",
  "library_items",
  "publish_queue",
  "publish_logs",
  "api_connections",
  "admin_settings",
  "settings",
  "templates",
  "ai_brain_rules",
  "ai_prompt_templates",
  "ai_feedbacks",
  "system_logs",
];
