import type { ReactElement } from "react";
import { useEffect, useState } from "react";
import { AuthProvider, useAuth } from "./lib/auth";
import { DashboardPage } from "./pages/DashboardPage";
import { ConteudosPage } from "./pages/ConteudosPage";
import { AdminPage } from "./pages/AdminPage";
import { BibliotecaPage } from "./pages/BibliotecaPage";
import { CalendarioPage } from "./pages/CalendarioPage";
import { PlanejamentoPage } from "./pages/PlanejamentoPage";
type RouteKey = "dashboard" | "planejamento" | "conteudos" | "biblioteca" | "calendario" | "admin";
function currentHash(): RouteKey { const hash = window.location.hash.replace("#", "") as RouteKey; return hash || "dashboard"; }
function LoginScreen() { const { login } = useAuth(); const [user, setUser] = useState("rodrigo"); const [password, setPassword] = useState("rodrigo"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); return <main className="login-shell"><section className="login-card glass-card"><div className="brand-mark">MYINC</div><h1>Social Media AI</h1><p>Planejamento, geração, revisão e publicação com IA processada na Vercel.</p><form onSubmit={async (e) => { e.preventDefault(); setLoading(true); setError(""); try { await login(user, password); } catch (err) { setError(err instanceof Error ? err.message : "Falha no login"); } finally { setLoading(false); } }}><label>Login ou e-mail<input value={user} onChange={(e) => setUser(e.target.value)} /></label><label>Senha<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error ? <div className="alert error">{error}</div> : null}<button disabled={loading} className="primary-btn">{loading ? "Entrando..." : "Entrar"}</button></form></section></main>; }
function Shell() { const auth = useAuth(); const [route, setRoute] = useState<RouteKey>(currentHash()); useEffect(() => { const listener = () => setRoute(currentHash()); window.addEventListener("hashchange", listener); return () => window.removeEventListener("hashchange", listener); }, []); if (auth.loading) return <div className="splash">Carregando MYINC...</div>; if (!auth.isAuthenticated) return <LoginScreen />; const pages: Record<RouteKey, ReactElement> = { dashboard: <DashboardPage />, planejamento: <PlanejamentoPage />, conteudos: <ConteudosPage />, biblioteca: <BibliotecaPage />, calendario: <CalendarioPage />, admin: <AdminPage /> }; return <div className="app-shell"><aside className="sidebar"><div className="sidebar-logo">MYINC<span>AI</span></div><nav><a className={route === "dashboard" ? "active" : ""} href="#dashboard">Dashboard</a><a className={route === "planejamento" ? "active" : ""} href="#planejamento">Planejamento</a><a className={route === "conteudos" ? "active" : ""} href="#conteudos">Conteúdos</a><a className={route === "biblioteca" ? "active" : ""} href="#biblioteca">Biblioteca</a><a className={route === "calendario" ? "active" : ""} href="#calendario">Calendário</a><a className={route === "admin" ? "active" : ""} href="#admin">Painel ADM</a></nav><button className="ghost-btn" onClick={auth.logout}>Sair</button></aside><main className="content-shell">{pages[route]}</main></div>; }
export function App() { return <AuthProvider><Shell /></AuthProvider>; }
