/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CerebroIaRouteImport } from './routes/cerebro-ia'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CerebroIaRoute = CerebroIaRouteImport.update({
  id: '/cerebro-ia',
  path: '/cerebro-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/cerebro-ia': typeof CerebroIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/cerebro-ia': typeof CerebroIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/cerebro-ia': typeof CerebroIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/planejamento': typeof PlanejamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/calendario'
    | '/cerebro-ia'
    | '/configuracoes'
    | '/conteudos'
    | '/login'
    | '/logs'
    | '/planejamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/calendario'
    | '/cerebro-ia'
    | '/configuracoes'
    | '/conteudos'
    | '/login'
    | '/logs'
    | '/planejamento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/calendario'
    | '/cerebro-ia'
    | '/configuracoes'
    | '/conteudos'
    | '/login'
    | '/logs'
    | '/planejamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  CerebroIaRoute: typeof CerebroIaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConteudosRoute: typeof ConteudosRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerebro-ia': {
      id: '/cerebro-ia'
      path: '/cerebro-ia'
      fullPath: '/cerebro-ia'
      preLoaderRoute: typeof CerebroIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  CerebroIaRoute: CerebroIaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConteudosRoute: ConteudosRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PlanejamentoRoute: PlanejamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
